var scoreCard = {
    score_0:{
        isScore:1,
        module:"1",
        params:JSON.stringify([{"text":"Text","yOffset":69,"xOffset":220,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":170,"height":51,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":69,"xOffset":160,"zorder":7,"style":{"fontSize":40,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FF000000"},"width":50,"height":51,"horizonAlign":"center","verticalAlign":"center"},{"text":"Text","yOffset":130,"xOffset":220,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":172,"height":51,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":130,"xOffset":160,"zorder":7,"style":{"fontSize":40,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FF000000"},"width":50,"height":51,"horizonAlign":"center","verticalAlign":"center"}]),
        peerId:"",
        relativePath:"images/score_bg1.png",
        size:"235x118",
        uploadContentType:"png",
        uploadFileName:"images/score_bg1.png",
        zorder:3
    },
    score_1:{
        isScore:1,
        module:"1",
        params:JSON.stringify([{"text":"Text","yOffset":66,"xOffset":331,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":128,"height":59,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":66,"xOffset":181,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":128,"height":59,"horizonAlign":"center","verticalAlign":"center"},{"text":"Text","yOffset":135,"xOffset":331,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":128,"height":59,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":135,"xOffset":181,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":128,"height":59,"horizonAlign":"center","verticalAlign":"center"}]),
        peerId:"",
        relativePath:"images/score_bg2.png",
        size:"294x130",
        uploadContentType:"png",
        uploadFileName:"images/score_bg2.png",
        zorder:3,
    },
    score_2:{
        isScore:1,
        module:"1",
        params:JSON.stringify([{"text":"Text","yOffset":69,"xOffset":744,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":181,"height":69,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":69,"xOffset":613,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FF000000"},"width":117,"height":69,"horizonAlign":"center","verticalAlign":"center"},{"text":"Text","yOffset":69,"xOffset":373,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":224,"height":69,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":69,"xOffset":240,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FF000000"},"width":120,"height":69,"horizonAlign":"center","verticalAlign":"center"},{"text":"1st","yOffset":143,"xOffset":629,"zorder":7,"style":{"fontSize":40,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":125,"height":40,"horizonAlign":"center","verticalAlign":"center"}]),
        peerId:"",
        relativePath:"images/score_bg3.png",
        size:"725x118",
        uploadContentType:"png",
        uploadFileName:"images/score_bg3.png",
        zorder:3
    },
    score_3:{
        isScore:1,
        module:"1",
        params:JSON.stringify([{"text":"Text","yOffset":69,"xOffset":584,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":141,"height":56,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":69,"xOffset":496,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":91,"height":56,"horizonAlign":"center","verticalAlign":"center"},{"text":"Text","yOffset":69,"xOffset":344,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":152,"height":56,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":69,"xOffset":253,"zorder":7,"style":{"fontSize":48,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":91,"height":56,"horizonAlign":"center","verticalAlign":"center"},{"text":"AGG","yOffset":127,"xOffset":603,"zorder":7,"style":{"fontSize":32,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":109,"height":35,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":127,"xOffset":477,"zorder":7,"style":{"fontSize":32,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":53,"height":35,"horizonAlign":"center","verticalAlign":"center"},{"text":"0","yOffset":127,"xOffset":413,"zorder":7,"style":{"fontSize":32,"backgroundColor":"00000000","fontName":"SimHei","foregroundColor":"FFFFFFFF"},"width":40,"height":35,"horizonAlign":"center","verticalAlign":"center"}]),
        peerId:"",
        relativePath:"images/score_bg5.png",
        size:"541x94",
        uploadContentType:"png",
        uploadFileName:"images/score_bg5.png",
        zorder:3
    }
}
var textAjaxParams = {
    zh_text:{
        "text":"请在此输入你的文本",
        "yOffset":783,
        "xOffset":1000,
        "style":{
            "fontSize":93,
            "backgroundColor":"00000000",
            "fontName":"SimHei",
            "foregroundColor":"FF000000"
        },
        "zorder":2,
        "width":837,
        "height":107,
        "horizonAlign":"center",
        "verticalAlign":"center"
    },
    en_text:{
        "text":"Please input your text here",
        "yOffset":783,
        "xOffset":600,
        "style":{
            "fontSize":93,
            "backgroundColor":"00000000",
            "fontName":"SimHei",
            "foregroundColor":"FF000000"
        },
        "zorder":2,
        "width":1255,
        "height":107,
        "horizonAlign":"center",
        "verticalAlign":"center"
    }
}